### ISSUE TITLE
Nuget package causes build warnings if used by .NET Core applications

### ISSUE THREAD

**Issue by andrewjsaid** [scottschluer/geolocation#10]
Hi,

This library is really great and easy to use - so first thank you.

It's not a big deal, but when referencing the package downloaded from NuGet, I receive this warning when building my project.

```
Warning	NU1701	Package 'Geolocation 1.1.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
```

This is a shame because I see that there already is a project which is based upon .NET Standard. This issue could be fixed if the files inside the NuGet package were just rebuild targeting the .NET Standard.

Thanks,
Andrew

**Comment by andrewjsaid** [comment]
A temporary solution is to suppress error message in csproj file as follows
```
<PropertyGroup><NoWarn>NU1701</NoWarn></PropertyGroup>
```

Are there any plans to follow up on this issue?

**Comment by andmos** [comment]
Running in to the same issue. In case you don't have the time to publish a proper .NET Standard package, I think I'll copy the code in to my project, since I run on Linux.

**Comment by hrai-domain** [comment]
I came here with the same issue. Is there any plans to upgrade this nuget to .NET Standard. Or would you like some help on this?

**Comment by scottschluer** [comment]
Closed with https://github.com/scottschluer/geolocation/issues/11

**Comment by andrewjsaid** [comment]
Thank you very much!
