### ISSUE TITLE
Rebuild NuGet package targeting both .NET Core and .NET Framework

### ISSUE THREAD

**Issue by jchristn** [scottschluer/geolocation#11]
Hi @scottschluer I hope you are well.  If you're open to it I'm happy to build an updated NuGet package for you that targets both .NET Core and .NET Framework, if you'd be interested.  Selfishly, it would help me, too.  If not, please feel free to close the issue.

**Comment by scottschluer** [comment]
Would love the help. I've moved on to managing software engineers rather than coding myself and haven't had the time to maintain this repo like I should. If you want to open a PR, I'll review/merge as soon as I can!

**Comment by jchristn** [comment]
Done sir, PR sent.  There is only one minor warning with a soon-to-be-deprecated method in your unit tests, since I had to uprev to .NET Core 2.0 and .NET Framework 4.5.1.  But, I collapsed into a single project and also added XML documentation.  NuGet package is in /bin/release/geolocation.1.2.0.nupkg.  Cheers, Joel

**Comment by jchristn** [comment]
Hi @scottschluer if it's easier for you I can upload this under my NuGet account - but didn't want to do it without asking you (for obvious reasons).  Let me know either way.  Thanks!

**Comment by rschiefer** [comment]
I also need an updated nuget package with all the latest PRs.

**Comment by hrai-domain** [comment]
@jchristn, it looks like the owner wants the PR raised against this repo. Do you mind raising a merge request with your changes if you already have them?

**Comment by jchristn** [comment]
I did that in a PR last year: https://github.com/scottschluer/geolocation/pull/12

**Comment by hrai-domain** [comment]
Looks like the repo is up-to-date and ready for .NET Standard 2.0 

Is there any reason why the new version of this nuget hasn't been released? Happy to help where I can.

**Comment by scottschluer** [comment]
@hrai-domain I haven't been paying much attention to this repo lately as I've been in a management role at work and not doing any coding for the last couple of years. In all honesty, I haven't pushed anything to Nuget since the last time it was updated and I probably need a quick refresher on updating that package. I'll look into it in the next week or so. I should probably start paying a little more attention to this repo, looks like it's picked up in usage a bit.

**Comment by sunnysonic** [comment]
I'd love a new version too as all moved to net core and nuget only has an old version of this.

**Comment by jchristn** [comment]
@scottschluer would you be ok if I just published the updated package under my account?

**Comment by scottschluer** [comment]
Yeah apologies. How about if I make you a temporary owner for the NuGet package? If you send me your NuGet username, I'll add you and you can update that existing package.

**Comment by scottschluer** [comment]
@jchristn ^

**Comment by scottschluer** [comment]
Disregard, just updated the NuGet package. ;)

**Comment by scottschluer** [comment]
https://www.nuget.org/packages/Geolocation/1.2.0

**Comment by sunnysonic** [comment]
Awesome. Thanks so much!

________________________________
