### ISSUE TITLE
Nuget package build from debug mode

### ISSUE THREAD

**Issue by InsonusK** [scottschluer/geolocation#16]
In https://github.com/scottschluer/geolocation/blob/master/NuGet/Geolocation.nuspec file
There is such lines:
file src="..\Geolocation\bin\Debug\Geolocation.dll" target="lib\Geolocation.dll
file src="..\Geolocation\bin\Debug\Geolocation.pdb" target="lib\Geolocation.pdb" 

It mean that you nuget package build from debug mode, is not it?

**Comment by scottschluer** [comment]
Fixed with 999d10daf057586fc32b707213a582cc11057bf4
