### ISSUE TITLE
add coords of cities as static types (like in rust)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [scottschluer/geolocation#18]

**Comment by madelson** [comment]
Is this asking for a bunch of static fields like so?

```
public static class CityCoordinates
{
    public static Coordinate Paris => ...
=
}
```
?

If so, I can't say I'm a fan. I feel like that kind of data could be ambiguous (which point in the city to pick) or even shift over time; not a good fit for a utility library like this IMO.
